import React from 'react'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import axios  from 'axios'
const Home = () => {

    const [city, setCity] = useState('')
    const [weather, setWeather] = useState({})
    const [loading, setLoading] = useState(false)
    
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

    const fetchingData = async (e) => {
      e.preventDefault()
      const response = await axios.get(url)
      setWeather(response.data)
      // .weather[0].main
    }


  return (
    <div>
      <Head>
            <title>WeatherApp-Next</title>
            <meta name="description" content="Generated by create next app"></meta>
      </Head>

      <div className='absolute top-0 bottom-0 right-0 left-0 text-white bg-black/40 z-10'></div>

          <Image 
            src='/valentin-muller-bWtd1ZyEy6w-unsplash.jpg' 
            alt="weather"
            fill
          />

        <div className='relative flex justify-between items-center text-white max-w-[500px] m-auto pt-4 z-10'>
            <form onSubmit={fetchingData} className='flex justify-between items-centers w-full p-3 border border-gray rounded-md m-auto'>
              <div>
                <input 
                className='p-2 bg-transparent focus:outline-none border-none text-white text-2xl' 
                onChange={(e) => setCity(e.target.value)} type='text' 
                placeholder='Search City'
                />
              </div>
                <button onClick={fetchingData} className='text-2xl'>Search</button>
            </form>
          </div>
    </div>
  )
}

export default Home
